# Generated by Django 5.1.3 on 2024-12-02 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('cover', models.ImageField(blank=True, upload_to='coffee_covers/')),
            ],
            options={
                'verbose_name': 'coffee',
                'verbose_name_plural': 'Coffee',
                'ordering': ('name',),
            },
        ),
    ]
