# Generated by Django 5.1.3 on 2024-11-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ('name',), 'verbose_name': 'coffee', 'verbose_name_plural': 'coffees'},
        ),
        migrations.AddField(
            model_name='coffee',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
