# Generated by Django 5.1.3 on 2024-11-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_coffee_options_coffee_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ('name',), 'verbose_name': 'coffee', 'verbose_name_plural': 'Coffee'},
        ),
    ]
