# Generated by Django 5.1.3 on 2024-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_coffee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
