# Generated by Django 5.1.3 on 2024-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_coffee_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='cover',
            field=models.ImageField(blank=True, upload_to='coffee_covers/'),
        ),
    ]
